
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-18T11:54:11-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b4c6e0f57b6a1fcd7c420c30630586a18aaa65a",
 "version": "3.15.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
